"""1

Revision ID: 10cce3180d41
Revises: 34c6d7e3606a
Create Date: 2025-04-25 11:21:38.943476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10cce3180d41'
down_revision: Union[str, None] = '34c6d7e3606a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cameras', 'url')

    # Используем batch mode для добавления уникального ограничения
    with op.batch_alter_table('courts') as batch_op:
        batch_op.create_unique_constraint('uq_courts_name', ['name'])

    op.add_column('videos', sa.Column('public', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'public')

    # Используем batch mode для удаления уникального ограничения
    with op.batch_alter_table('courts') as batch_op:
        batch_op.drop_constraint('uq_courts_name', type_='unique')

    op.add_column('cameras', sa.Column('url', sa.String(), nullable=True))
    # ### end Alembic commands ###
