"""Initial migration

Revision ID: 34c6d7e3606a
Revises: 
Create Date: 2025-04-15 00:28:30.815469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34c6d7e3606a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cameras', sa.Column('ip', sa.String(), nullable=False))
    op.add_column('cameras', sa.Column('port', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cameras', 'port')
    op.drop_column('cameras', 'ip')
    # ### end Alembic commands ###
