"""3

Revision ID: ad61b37b838f
Revises: cf48e62d86e6
Create Date: 2025-05-18 23:09:02.285031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad61b37b838f'
down_revision: Union[str, None] = 'cf48e62d86e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_password', sa.String(), nullable=True))
    op.drop_column('users', 'current_pasword')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_pasword', sa.VARCHAR(), nullable=True))
    op.drop_column('users', 'current_password')
    # ### end Alembic commands ###
