"""2

Revision ID: cf48e62d86e6
Revises: 10cce3180d41
Create Date: 2025-05-18 20:37:10.458837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf48e62d86e6'
down_revision: Union[str, None] = '10cce3180d41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courts', sa.Column('totp_secret', sa.String(), nullable=True))
    op.drop_column('courts', 'current_password')
    op.drop_column('courts', 'previous_password')
    op.drop_column('courts', 'password_expiration_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courts', sa.Column('password_expiration_date', sa.DATETIME(), nullable=False))
    op.add_column('courts', sa.Column('previous_password', sa.VARCHAR(), nullable=False))
    op.add_column('courts', sa.Column('current_password', sa.VARCHAR(), nullable=False))
    op.drop_column('courts', 'totp_secret')
    # ### end Alembic commands ###
